"""empty message

Revision ID: 183d9c16da3c
Revises: 
Create Date: 2025-11-18 14:31:09.253107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '183d9c16da3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('entries',
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('load', sa.Integer(), server_default='0', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('load >= 0', name='load_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_id'), 'entries', ['id'], unique=False)
    op.create_index(op.f('ix_entries_user_id'), 'entries', ['user_id'], unique=False)
    op.create_table('hold_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exercise', sa.Enum('PLANK', 'HANGING', 'SQUAT_HOLD', name='holdentrytype'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reps_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('exercise', sa.Enum('PUSH_UPS', 'PULL_UPS', 'CHIN_UPS', 'SQUATS', 'ROMANIAN_DEADLIFTS', 'ROWS', 'TIBIALIS_RAISES', 'CALF_RAISES', 'NORDIC_CURLS', 'REVERSE_NORDIC_CURLS', 'ABS_ROLL_OUTS', name='repsentrytype'), nullable=False),
    sa.CheckConstraint('reps >= 0', name='reps_positive'),
    sa.ForeignKeyConstraint(['id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reps_entries')
    op.drop_table('hold_entries')
    op.drop_index(op.f('ix_entries_user_id'), table_name='entries')
    op.drop_index(op.f('ix_entries_id'), table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
